repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.9
  hooks:
    - id: ruff-check
    - id: ruff-format
# doesn't exist (yet)
# - repo: https://github.com/astral-sh/ty-pre-commit

