from dataclasses import dataclass, field
from hashlib import sha256
from operator import add
from pathlib import Path
from typing import Self

from itrx import Itr

from xenoform_rs import __version__ as version
from xenoform_rs.config import get_config
from xenoform_rs.errors import RustConfigError
from xenoform_rs.utils import rustfmt

_CARGO_TEMPLATE = """
# Generated by xenoform-rs {version}. DO NOT EDIT DIRECTLY.

[package]
name = "{module_name}"
edition = "{edition}"

[lib]
crate-type = ["cdylib"]

[profile.release]
{profile_overrides}

[dependencies]
{dependencies}
pyo3 = {{ version = "{pyo3_version}", features = ["extension-module", "abi3-py312"] }}
"""


_MODULE_TEMPLATE = """
#![allow(non_upper_case_globals)]
{modules}

#[pyo3::pymodule{freethreaded}]
mod {module_name} {{
use pyo3::prelude::*;
    {use_statements}
    {crate_use_statements}

    #[pymodule_export]
    const __doc__: &str = "{module_name} module generated by xenoform-rs {version}";

    #[pymodule_export]
    const __checksum__: &str = "__HASH__";

    {function_definitions}
}}
"""


_FUNCTION_DEFINITION_TEMPLATE = """
{help}
#[pyfunction]
#[pyo3 (signature=({arg_defs}))]
fn {function_name}<'py>{function_body}

"""


def _format_help(help: str | None) -> str:
    if not help:
        return ""
    return Itr((help).split("\n")).map(lambda line: f"/// {line}").intersperse("\n").reduce(add)


@dataclass(frozen=True)
class FunctionSpec:
    """
    Dataclass defining a function
    """

    name: str
    body: str
    py: bool
    arg_annotations: str
    scope: tuple[str, ...]
    help: str | None = None

    def qualified_name(self) -> str:
        if self.scope:
            return f"_{'_'.join(self.scope)}_{self.name}"
        return f"_{self.name}"


def _append_profile(existing: dict[str, str], new: dict[str, str]) -> dict[str, str]:
    common_keys = existing.keys() & new.keys()
    for k in common_keys:
        if existing[k] != new[k]:
            raise RustConfigError(f"Conflicting profile values for {k}: {existing[k]} vs {new[k]}")
    return existing | new


@dataclass
class ModuleSpec:
    """
    Dataclass for accumulating functions to be built within a module
    """

    functions: set[FunctionSpec] = field(default_factory=set[FunctionSpec])
    deps: set[str] = field(default_factory=set[str])
    uses: set[str] = field(default_factory=set[str])
    profile: dict[str, str] = field(default_factory=dict[str, str])
    edition: str | None = None  # will default to "2024"
    modules: set[Path] = field(default_factory=set[Path])

    def add_function(
        self,
        function: FunctionSpec,
        *,
        deps: list[str] | None = None,
        uses: list[str] | None = None,
        profile: dict[str, str] | None = None,
        edition: str | None = None,
        modules: list[Path] | None = None,
    ) -> Self:
        self.functions.add(function)
        self.deps |= set(deps or [])
        self.uses |= set(uses or [])
        self.profile = _append_profile(self.profile, profile or {})
        self.modules |= set(modules or [])
        if edition and self.edition and edition != self.edition:
            raise RustConfigError(f"Incompatible edition values: {edition} when {self.edition} has already been set")
        self.edition = edition or self.edition
        return self

    def make_source(self, module_name: str) -> tuple[str, str, str]:
        module = _CARGO_TEMPLATE.format(
            version=version,
            pyo3_version=get_config().pyo3_version,
            module_name=module_name,
            edition=self.edition or "2024",  # only default at the point when Cargo.toml is generated
            profile_overrides="\n".join(f'{k} = "{v}"' for k, v in self.profile.items()),
            dependencies="\n".join(self.deps),
        )

        # sort to prevent rebuilding when nothing has changed but the function ordering
        function_defs = "\n".join(
            sorted(
                _FUNCTION_DEFINITION_TEMPLATE.format(
                    function_name=f.qualified_name(),
                    # lifetime="<'py>" if f.lifetime else "",
                    function_body=f.body,
                    arg_defs=f.arg_annotations,
                    help=_format_help(f.help),
                )
                for f in self.functions
            )
        )

        # create the code without the hash
        code = _MODULE_TEMPLATE.format(
            version=version,
            module_name=module_name,
            modules="\n".join(f"pub mod {m.stem};" for m in self.modules),
            freethreaded="(gil_used = true)" if get_config().disable_ft else "(gil_used = false)",
            use_statements="\n".join(f"use {u};" for u in self.uses),
            crate_use_statements="\n".join(f"use crate::{m.stem};" for m in self.modules),
            function_definitions=function_defs,
        )

        code = rustfmt(code)

        hash = sha256(module.encode("utf-8") + code.encode("utf-8"))
        for m in self.modules:
            hash.update(m.read_bytes())

        return module, code, hash.hexdigest()
