from dataclasses import dataclass, field
from hashlib import sha256
from operator import add
from typing import Self

from itrx import Itr

from xenoform_rs import __version__ as version
from xenoform_rs.config import get_config
from xenoform_rs.utils import rustfmt

_CARGO_TEMPLATE = """
# Generated by xenoform-rs {version}. DO NOT EDIT DIRECTLY.

[package]
name = "{module_name}"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
{dependencies}
pyo3 = {{ version = "{pyo3_version}", features = ["extension-module", "abi3-py312"] }}
"""


_MODULE_TEMPLATE = """
#![allow(non_upper_case_globals)]
#[pyo3::pymodule{freethreaded}]
mod {module_name} {{
use pyo3::prelude::*;
    {use_statements}

    #[pymodule_export]
    const __doc__: &str = "{module_name} module generated by xenoform-rs {version}";

    #[pymodule_export]
    const __checksum__: &str = "__HASH__";

    {function_definitions}
}}
"""


_FUNCTION_DEFINITION_TEMPLATE = """
{help}
#[pyfunction]
#[pyo3 (signature=({arg_defs}))]
fn {function_name}<'py>{function_body}

"""


def _format_help(help: str | None) -> str:
    if not help:
        return ""
    return Itr((help).split("\n")).map(lambda line: f"/// {line}").intersperse("\n").reduce(add)


@dataclass(frozen=True)
class FunctionSpec:
    """
    Dataclass defining a function
    """

    name: str
    body: str
    py: bool
    arg_annotations: str
    scope: tuple[str, ...]
    help: str | None = None

    def qualified_name(self) -> str:
        if self.scope:
            return f"_{'_'.join(self.scope)}_{self.name}"
        return f"_{self.name}"


@dataclass
class ModuleSpec:
    """
    Dataclass for accumulating functions to be built within a module
    """

    functions: set[FunctionSpec] = field(default_factory=set[FunctionSpec])
    deps: set[str] = field(default_factory=set[str])
    uses: set[str] = field(default_factory=set[str])

    def add_function(
        self,
        function: FunctionSpec,
        *,
        deps: list[str] | None = None,
        uses: list[str] | None = None,
    ) -> Self:
        self.functions.add(function)
        self.deps |= set(deps or [])
        self.uses |= set(uses or [])
        return self

    def make_source(self, module_name: str) -> tuple[str, str, str]:
        # uses = Itr(group_headers(self.headers)).flatten().fold("", lambda hs, h: hs + f"#include {h}\n")

        module = _CARGO_TEMPLATE.format(
            version=version,
            pyo3_version=get_config().pyo3_version,
            module_name=module_name,
            dependencies="\n".join(self.deps),
        )

        # sort to prevent rebuilding when nothing has changed but the function ordering
        function_defs = "\n".join(
            sorted(
                _FUNCTION_DEFINITION_TEMPLATE.format(
                    function_name=f.qualified_name(),
                    # lifetime="<'py>" if f.lifetime else "",
                    function_body=f.body,
                    arg_defs=f.arg_annotations,
                    help=_format_help(f.help),
                )
                for f in self.functions
            )
        )

        # create the code without the hash
        code = _MODULE_TEMPLATE.format(
            version=version,
            module_name=module_name,
            freethreaded="(gil_used = true)" if get_config().disable_ft else "(gil_used = false)",
            use_statements="\n".join(f"use {u};" for u in self.uses),
            function_definitions=function_defs,
        )

        code = rustfmt(code)

        # return code and hash
        return module, code, sha256(module.encode() + code.encode()).hexdigest()
